-- MySQL Script generated by MySQL Workbench
-- 07/06/16 15:51:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`location` (
  `idLocation` INT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  UNIQUE INDEX `idLocations_UNIQUE` (`idLocation` ASC),
  PRIMARY KEY (`idLocation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_details` (
  `idUser_details` INT NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(6) NOT NULL,
  `location_id` INT NOT NULL,
  `email` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idUser_details`),
  UNIQUE INDEX `idPerson_UNIQUE` (`idUser_details` ASC),
  INDEX `fk_person_location1_idx` (`location_id` ASC),
  CONSTRAINT `fk_person_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `mydb`.`location` (`idLocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(12) NOT NULL,
  `password` VARCHAR(12) NOT NULL,
  `time_registration` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_details_id` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_account_UNIQUE` (`idUser` ASC),
  INDEX `fk_user_user_details1_idx` (`user_details_id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  CONSTRAINT `fk_user_user_details1`
    FOREIGN KEY (`user_details_id`)
    REFERENCES `mydb`.`user_details` (`idUser_details`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`groups` (
  `idGroup` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`idGroup`),
  UNIQUE INDEX `idgroup_UNIQUE` (`idGroup` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dialog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dialog` (
  `idDialog` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `text` VARCHAR(500) NOT NULL,
  `time_creation` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `group_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`idDialog`),
  UNIQUE INDEX `idDialog_UNIQUE` (`idDialog` ASC),
  INDEX `fk_dialog_group1_idx` (`group_id` ASC),
  INDEX `fk_dialog_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_dialog_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `mydb`.`groups` (`idGroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dialog_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dialog_message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dialog_message` (
  `idDialog_message` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(500) NOT NULL,
  `time_creation` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dialog_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`idDialog_message`),
  UNIQUE INDEX `idMessages_UNIQUE` (`idDialog_message` ASC),
  INDEX `fk_Messages_Dialog1_idx` (`dialog_id` ASC),
  INDEX `fk_Messages_User1_idx` (`user_id` ASC),
  CONSTRAINT `fk_Messages_Dialog1`
    FOREIGN KEY (`dialog_id`)
    REFERENCES `mydb`.`dialog` (`idDialog`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Messages_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`message` (
  `idMessage` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(500) NOT NULL,
  `time_creation` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sender_id` INT NOT NULL,
  `receiver_id` INT NOT NULL,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idMessage`),
  UNIQUE INDEX `idmessage_UNIQUE` (`idMessage` ASC),
  INDEX `fk_message_user1_idx` (`sender_id` ASC),
  INDEX `fk_message_user2_idx` (`receiver_id` ASC),
  CONSTRAINT `fk_message_user1`
    FOREIGN KEY (`sender_id`)
    REFERENCES `mydb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_user2`
    FOREIGN KEY (`receiver_id`)
    REFERENCES `mydb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`post` (
  `idPost` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(500) NOT NULL,
  `time_creation` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`idPost`),
  UNIQUE INDEX `idstatus_UNIQUE` (`idPost` ASC),
  INDEX `fk_status_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_status_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comment` (
  `idComment` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(500) NOT NULL,
  `time_creation` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `post_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`idComment`),
  UNIQUE INDEX `idComment_UNIQUE` (`idComment` ASC),
  INDEX `fk_Comment_status1_idx` (`post_id` ASC),
  INDEX `fk_comment_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_Comment_status1`
    FOREIGN KEY (`post_id`)
    REFERENCES `mydb`.`post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`friend_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`friend_list` (
  `idFriend` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `friend_id` INT NOT NULL,
  PRIMARY KEY (`idFriend`),
  INDEX `fk_friend_list_user1_idx` (`user_id` ASC),
  INDEX `fk_friend_list_user2_idx` (`friend_id` ASC),
  UNIQUE INDEX `idFriend_UNIQUE` (`idFriend` ASC),
  CONSTRAINT `fk_friend_list_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_friend_list_user2`
    FOREIGN KEY (`friend_id`)
    REFERENCES `mydb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

insert into groups (title,description) VALUES ('Bike check/Байк чек','send bike for people checking/Покажи свой байк');
insert into groups (title,description) VALUES ('Buying bikes/Покупка велосипедов','write you search response for bike/Размести обьявление о покупке велосипеда');
insert into groups (title,description) VALUES ('Trade bikes/Продажа велосипедов','write you bike for trade/размести обьявление о продаже велосипеда');
insert into groups (title,description) VALUES ('Speaking about bikes/Велоразговоры','any question about bikes/всё об велосипедах');
insert into groups (title,description) VALUES ('Speaking about everything/разговор обо всём','spam group/различный спам');
insert into groups (title,description) VALUES ('Bike travels/Велотуризм','travel speaking/разговор об путешевствиях');
