-- MySQL Script generated by MySQL Workbench
-- 03/30/16 22:20:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hotel_admin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hotel_admin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotel_admin` DEFAULT CHARACTER SET utf8 ;
USE `hotel_admin` ;

-- -----------------------------------------------------
-- Table `hotel_admin`.`guest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_admin`.`guest` (
  `idGuest` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idGuest`),
  UNIQUE INDEX `idGuest_UNIQUE` (`idGuest` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_admin`.`hotel_room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_admin`.`hotel_room` (
  `idHotelRoom` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(10) NOT NULL,
  `room_price` INT NOT NULL,
  `sleeping_number` INT NOT NULL,
  `star_category` SMALLINT NOT NULL,
  `busy` TINYINT(1) NOT NULL,
  `status` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idHotelRoom`),
  UNIQUE INDEX `idHotelRoom_UNIQUE` (`idHotelRoom` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_admin`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_admin`.`orders` (
  `idOrders` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `guest_id` INT NOT NULL,
  `hotel_room_id` INT NOT NULL,
  `date_arrive` DATE NOT NULL,
  `date_departure` DATE NOT NULL,
  `paid_orders` TINYINT(1) NOT NULL DEFAULT 0,
  INDEX `fk_guest_to_hotel_room_guest1_idx` (`guest_id` ASC),
  PRIMARY KEY (`idOrders`),
  INDEX `fk_orders_hotel_room1_idx` (`hotel_room_id` ASC),
  UNIQUE INDEX `idOrders_UNIQUE` (`idOrders` ASC),
  CONSTRAINT `fk_guest_to_hotel_room_guest1`
    FOREIGN KEY (`guest_id`)
    REFERENCES `hotel_admin`.`guest` (`idGuest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_hotel_room1`
    FOREIGN KEY (`hotel_room_id`)
    REFERENCES `hotel_admin`.`hotel_room` (`idHotelRoom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_admin`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_admin`.`service` (
  `idService` INT NOT NULL AUTO_INCREMENT,
  `orders_id` INT ZEROFILL NOT NULL,
  `name_service` VARCHAR(25) NOT NULL,
  `service_price` INT NOT NULL,
  `paid_service` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idService`),
  UNIQUE INDEX `idService_UNIQUE` (`idService` ASC),
  INDEX `fk_service_orders1_idx` (`orders_id` ASC),
  CONSTRAINT `fk_service_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `hotel_admin`.`orders` (`idOrders`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS; 



INSERT INTO guest (name) VALUES ('Paul');
INSERT INTO guest (name) VALUES ('Linda');
INSERT INTO guest (name) VALUES ('Archie');
INSERT INTO guest (name) VALUES ('Serinity');
INSERT INTO guest (name) VALUES ('Nobel');
INSERT INTO guest (name) VALUES ('Andrea');
INSERT INTO guest (name) VALUES ('Stephany');
INSERT INTO guest (name) VALUES ('Don');
INSERT INTO guest (name) VALUES ('Tina');


INSERT INTO hotel_room (number,room_price,sleeping_number,star_category, busy, status) VALUES ('101',80,1,5,false,true);
INSERT INTO hotel_room (number,room_price,sleeping_number,star_category, busy, status) VALUES ('102',50,2,5,false,true);
INSERT INTO hotel_room (number,room_price,sleeping_number,star_category, busy, status) VALUES ('201',75,3,5,true,true);
INSERT INTO hotel_room (number,room_price,sleeping_number,star_category, busy, status) VALUES ('301',200,1,5,true,true);
INSERT INTO hotel_room (number,room_price,sleeping_number,star_category, busy, status) VALUES ('103',65,1,2,false,true);


INSERT INTO orders (guest_id,hotel_room_id,date_arrive,date_departure) VALUES (1,5,'2015-12-15','2015-12-18');
INSERT INTO orders (guest_id,hotel_room_id,date_arrive,date_departure) VALUES (3,2,'2015-12-16','2015-12-25');
INSERT INTO orders (guest_id,hotel_room_id,date_arrive,date_departure) VALUES (4,3,'2015-12-15','2015-12-24');
INSERT INTO orders (guest_id,hotel_room_id,date_arrive,date_departure) VALUES (5,3,'2015-12-15','2015-12-24');
INSERT INTO orders (guest_id,hotel_room_id,date_arrive,date_departure) VALUES (6,3,'2015-12-15','2015-12-24');
INSERT INTO orders (guest_id,hotel_room_id,date_arrive,date_departure) VALUES (7,4,'2015-01-17','2015-12-19');


INSERT INTO service (orders_id,name_service,service_price) VALUES (1,'Diner',10);
INSERT INTO service (orders_id,name_service,service_price) VALUES (1,'Cleaning',5);
INSERT INTO service (orders_id,name_service,service_price) VALUES (2,'Parking',8);
INSERT INTO service (orders_id,name_service,service_price) VALUES (3,'Bar',5);
INSERT INTO service (orders_id,name_service,service_price) VALUES (1,'Swimming',40);
INSERT INTO service (orders_id,name_service,service_price) VALUES (2,'Free walk',90)     ;
INSERT INTO service (orders_id,name_service,service_price) VALUES (2,'Diner',10);




