-- MySQL Script generated by MySQL Workbench
-- 05/29/16 17:37:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_role` (
  `id_user_role` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_user_role`),
  UNIQUE INDEX `idRole_UNIQUE` (`id_user_role` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(16) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `time_registration` DATE NOT NULL,
  `lang` VARCHAR(5) NULL DEFAULT 'eng',
  `user_role_id` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_account_UNIQUE` (`idUser` ASC),
  INDEX `fk_user_user_type1_idx` (`user_role_id` ASC),
  CONSTRAINT `fk_user_user_type1`
    FOREIGN KEY (`user_role_id`)
    REFERENCES `mydb`.`user_role` (`id_user_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`location` (
  `idLocations` INT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  UNIQUE INDEX `idLocations_UNIQUE` (`idLocations` ASC),
  PRIMARY KEY (`idLocations`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_details` (
  `idUser_details` INT NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `date_of_birth` DATE NULL,
  `gender` VARCHAR(6) NOT NULL,
  `phone_number` INT NULL,
  `user_id` INT NOT NULL,
  `location_id` INT NOT NULL,
  PRIMARY KEY (`idUser_details`),
  UNIQUE INDEX `idPerson_UNIQUE` (`idUser_details` ASC),
  INDEX `fk_person_user1_idx` (`user_id` ASC),
  INDEX `fk_person_location1_idx` (`location_id` ASC),
  CONSTRAINT `fk_person_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `mydb`.`location` (`idLocations`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`group` (
  `idGroup` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `time_creation` DATE NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`idGroup`),
  UNIQUE INDEX `idgroup_UNIQUE` (`idGroup` ASC),
  INDEX `fk_group_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_group_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dialog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dialog` (
  `idDialog` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `text` VARCHAR(500) NOT NULL,
  `time_creation` DATE NOT NULL,
  `group_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`idDialog`),
  UNIQUE INDEX `idDialog_UNIQUE` (`idDialog` ASC),
  INDEX `fk_dialog_group1_idx` (`group_id` ASC),
  INDEX `fk_dialog_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_dialog_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `mydb`.`group` (`idGroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dialog_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dialog_message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dialog_message` (
  `idDialog_messages` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(500) NOT NULL,
  `time_creation` DATE NOT NULL,
  `dialog_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`idDialog_messages`),
  UNIQUE INDEX `idMessages_UNIQUE` (`idDialog_messages` ASC),
  INDEX `fk_Messages_Dialog1_idx` (`dialog_id` ASC),
  INDEX `fk_Messages_User1_idx` (`user_id` ASC),
  CONSTRAINT `fk_Messages_Dialog1`
    FOREIGN KEY (`dialog_id`)
    REFERENCES `mydb`.`dialog` (`idDialog`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Messages_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`language` (
  `idLang` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(5) NOT NULL,
  `code` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`idLang`),
  UNIQUE INDEX `idlang_UNIQUE` (`idLang` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`message` (
  `idMessage` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(500) NOT NULL,
  `time_creation` DATE NOT NULL,
  `is_read` TINYINT(1) NULL DEFAULT 0,
  `sender_id` INT NOT NULL,
  `receiver_id` INT NOT NULL,
  PRIMARY KEY (`idMessage`),
  UNIQUE INDEX `idmessage_UNIQUE` (`idMessage` ASC),
  INDEX `fk_message_user1_idx` (`sender_id` ASC),
  INDEX `fk_message_user2_idx` (`receiver_id` ASC),
  CONSTRAINT `fk_message_user1`
    FOREIGN KEY (`sender_id`)
    REFERENCES `mydb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_user2`
    FOREIGN KEY (`receiver_id`)
    REFERENCES `mydb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`post` (
  `idPost` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(500) NOT NULL,
  `time_creation` DATE NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`idPost`),
  UNIQUE INDEX `idstatus_UNIQUE` (`idPost` ASC),
  INDEX `fk_status_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_status_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comment` (
  `idComment` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(500) NOT NULL,
  `time_creation` DATE NOT NULL,
  `post_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`idComment`),
  UNIQUE INDEX `idComment_UNIQUE` (`idComment` ASC),
  INDEX `fk_Comment_status1_idx` (`post_id` ASC),
  INDEX `fk_comment_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_Comment_status1`
    FOREIGN KEY (`post_id`)
    REFERENCES `mydb`.`post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;








-- -----------------------------------------------------
-- Table `mydb`.`group_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`group_list` (
  `user_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `group_id`),
  INDEX `fk_user_has_group_group1_idx` (`group_id` ASC),
  INDEX `fk_user_has_group_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_group_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_group_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `mydb`.`group` (`idGroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`friend_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`friend_list` (
  `user_id` INT NOT NULL,
  `friend_id` INT NOT NULL,
  `confirmed` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`user_id`, `friend_id`),
  INDEX `fk_user_has_user_user2_idx` (`friend_id` ASC),
  INDEX `fk_user_has_user_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_user_user2`
    FOREIGN KEY (`friend_id`)
    REFERENCES `mydb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;