-- MySQL Script generated by MySQL Workbench
-- 03/09/16 23:10:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb

CREATE DATABASE IF NOT EXISTS mydb;

USE mydb;

-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS product (
  maker VARCHAR(10) NOT NULL,
  model VARCHAR(50) NOT NULL PRIMARY KEY,
  type VARCHAR(50) NOT NULL
  )
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`laptop`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS laptop (
  ñode INT NOT NULL PRIMARY KEY,
  model VARCHAR(50) NOT NULL,
  speed SMALLINT NOT NULL,
  ram SMALLINT NOT NULL,
  hd REAL NOT NULL,
  price DOUBLE NULL,
  screen TINYINT NOT NULL,
    FOREIGN KEY (model) REFERENCES product (model)
	ON DELETE NO ACTION
    ON UPDATE NO ACTION
    )
     ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pc`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS pc (
  code INT NOT NULL PRIMARY KEY,
  model VARCHAR(50) NOT NULL,
  speed SMALLINT NOT NULL,
  ram SMALLINT NOT NULL,
  hd REAL NOT NULL,
  cd VARCHAR(10) NOT NULL,
  price DOUBLE NULL,
    FOREIGN KEY (model) REFERENCES product (model)
	ON DELETE NO ACTION
    ON UPDATE NO ACTION
    )
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`printer`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS printer (
  code INT NOT NULL PRIMARY KEY,
  model VARCHAR(50) NOT NULL,
  color CHAR(1) NOT NULL,
  type VARCHAR(10) NOT NULL,
  price DOUBLE NULL,
    FOREIGN KEY (model) REFERENCES product (model)
	ON DELETE NO ACTION
    ON UPDATE NO ACTION
   )
    ENGINE = InnoDB;
    
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;