'use strict';

socialNetworkApp.config(function ($translateProvider) {
  $translateProvider.translations('en', {
    TITLE: 'Hello',
    FOO: 'This is a message.',
    BUTTON_LANG_EN: 'eng',
    BUTTON_LANG_RU: 'russian',
    OLD_PASS:'Old password',
    NEW_PASS:'New password',
    CONF_PASS: 'Confirm Password',
    CHNG_PASS:'Change Password',
    CANCEL:"Cancel",
    DELETE:"Delete",
    EDIT:"Edit",
    SAVE:"Save",
    SHOW_ALL_COMMENTS:'Show All сomments :',
    COMMENT:'Comment',
    EDIT_PROFILE:'Edit profile',
    NAME:'Name',
    LAST_NAME:'Last Name',
    MALE:'Male',
    FEMALE:'Female',
    FRIENDS_TOTAL:'Friends total:',
    HOME:'Home:',
    FRIEND_REQUESTS:'Friend requests',
    APPROVE:'Approve',
    REJECT:'Reject',
    SEARCH:'Search',
    RESULT_TOTAL:'Result total',
    EDIT_PROFILE:'Edit profile',
    LOGOUT:'Logout',
    FRIEND:'Friend',
    FRIEND_REQUEST_PENDING:'Friend request pending',
    SEND_FRIEND_REQUEST:'Send friend request',
    LOGIN:'Login',
    USERNAME:'Username',
    PASSWORD:'Password',
    REGISTER:'Register',
    POST:'Post',
    BIRTHDAY_DATE:'Birthday date',
    CITY:'City',
    STATE:'State',
    COUNTRY:'Country',
    PHONE:'Phone',
	FRIENDS:'Friends',
    MY_PAGE:'My page',
    MY_FRIENDS:'My friends',
    MY_MESSAGES:'My messages',
    MY_GROUPS:'My groups',
    MY_EVENTS_NEWS:'My events/news',
    SETTINGS:'Settings'
  }),
  $translateProvider.translations('ru', {
    TITLE: 'Привет',
    FOO: '"Это сообщение.',
    BUTTON_LANG_EN: 'англ',
    BUTTON_LANG_RU: 'рус',
    OLD_PASS:'Cтарый пароль',
    NEW_PASS:'Новый пароль',
    CONF_PASS: 'Подтвердить пароль',
    CANCEL:"Отмена",
    DELETE:"Удалить",
    EDIT:"Редактировать",
    SAVE:"Сохранить",
    CHNG_PASS:'Сменить пароль',
    SHOW_ALL_COMMENTS:'Показать все комментарии :',
    COMMENT:'Комментировать',
    EDIT_PROFILE:'Ркдактировать профиль',
    NAME:'Имя',
    LAST_NAME:'Фамилия',
    MALE:'Мужской',
    FEMALE:'Женский',
    FRIENDS_TOTAL:'Всего друзей:',
    HOME:'Главная страница',
    FRIEND_REQUESTS:'Запросы в друзья',
    APPROVE:'Подтвердить',
    REJECT:'Отменить',
    SEARCH:'Поиск',
    RESULT_TOTAL:'Всего результатов',
    EDIT_PROFILE:'Редактировать профиль',
    LOGOUT:'Выйти',
    FRIEND:'Друг',
    FRIEND_REQUEST_PENDING:'Запрос в друзья',
    SEND_FRIEND_REQUEST:'Добавить в друзья',
    LOGIN:'Логирование',
    USERNAME:'Логин',
    PASSWORD:'Пароль',
    REGISTER:'Регистрация',
    POST:'Публикация',
    BIRTHDAY_DATE:'Дата рождения',
    CITY:'Город',
    STATE:'Область',
    COUNTRY:'Страна',
    PHONE:'Телефон',
	FRIENDS:'Друзья',
    MY_PAGE:'Моя страница',
    MY_FRIENDS:'Мои друзья',
    MY_MESSAGES:'Мои сообщения',
    MY_GROUPS:'Мои группы',
    MY_EVENTS_NEWS:'Мои события/новости',
    SETTINGS:'Настройки'


  });

  $translateProvider.useSanitizeValueStrategy(null);
  $translateProvider.preferredLanguage('en');
});


socialNetworkApp.controller('TransleteController', function TransleteController($scope, $translate) {
  $scope.changeLanguage = function (key) {
    $translate.use(key);
  };
});